version: '3.4'

services:
  testit2:
    image: testit2:dev
    container_name: testit2
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "testit2"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_testit2$
    volumes:
      - C:\Users\docto\source\repos\testit2\testit2:/app
      - C:\Users\docto\source\repos\testit2:/src
      - C:\Users\docto\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_testit2$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_testit2$ \"bin/Debug/netcoreapp2.1/testit2.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true